services:
  # PHP-FPM Service
  php:
    image: devilbox/php-fpm:8.2-mods
    container_name: openmageFront-php
    volumes:
      - ./src:/var/www
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: openmageFront-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  # Node.js Service for SCSS Compilation
  node:
    build: .
    container_name: openmageFront-node
    volumes:
      - ./src:/var/www
    command: npm run build-css -- --watch
    networks:
      - app-network

networks:
  app-network:
    driver: bridge